#!/usr/bin/env bash
# ============================================================================
# Qora Billing API — one-line self-host installer.
#
#   curl -fsSL https://raw.githubusercontent.com/JJQuispillo/SriYa/main/install.sh | bash
#
# What it does:
#   1. Checks Docker + Docker Compose are available.
#   2. Downloads docker-compose.prod.yml.
#   3. Generates strong random secrets into .env (kept if it already exists).
#   4. Starts the stack and waits for /health.
#
# Env overrides:
#   INSTALL_DIR   target directory (default: ./qora-billing)
#   BILLING_PORT  host port for the API (default: 8080)
#   REF           git ref to pull files from (default: main)
# ============================================================================
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/JJQuispillo/SriYa"
REF="${REF:-main}"
INSTALL_DIR="${INSTALL_DIR:-qora-billing}"
BILLING_PORT="${BILLING_PORT:-8080}"

info()  { printf '\033[1;34m==>\033[0m %s\n' "$1"; }
ok()    { printf '\033[1;32m✓\033[0m %s\n' "$1"; }
err()   { printf '\033[1;31m✗ %s\033[0m\n' "$1" >&2; }

# --- 1. Preflight ----------------------------------------------------------
command -v docker >/dev/null 2>&1 || { err "Docker not found. Install Docker first: https://docs.docker.com/get-docker/"; exit 1; }
if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose v2 not found. Update Docker or install the compose plugin."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  err "Docker daemon is not running. Start Docker and re-run."
  exit 1
fi
ok "Docker is ready"

# A secret generator that works without openssl too.
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n'
  else
    head -c 48 /dev/urandom | base64 | tr -d '\n/+=' | head -c 44
  fi
}

# --- 2. Files --------------------------------------------------------------
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
info "Installing into $(pwd)"

info "Downloading docker-compose.yml"
curl -fsSL "$REPO_RAW/$REF/docker-compose.prod.yml" -o docker-compose.yml
ok "Compose file ready"

# --- 3. Secrets / .env -----------------------------------------------------
if [ -f .env ]; then
  ok ".env already exists — leaving it untouched"
else
  info "Generating .env with random secrets"
  cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Review CORS_ORIGIN_0 before exposing this service publicly.

BILLING_API_PORT=${BILLING_PORT}

# ─── Database ─────────────────────────────────────────────
BILLING_DB_USER=billing_user
BILLING_DB_PASSWORD=$(gen_secret)

# ─── Service-to-service auth ──────────────────────────────
SERVICE_AUTH_TOKEN=$(gen_secret)

# ─── Certificate-key encryption (at rest) ─────────────────
ENCRYPTION_KEY=$(gen_secret)

# ─── CORS ─────────────────────────────────────────────────
CORS_ORIGIN_0=http://localhost:3000
EOF
  chmod 600 .env
  ok "Secrets written to .env (chmod 600)"
fi

# --- 4. Launch -------------------------------------------------------------
info "Pulling images and starting the stack"
docker compose pull
docker compose up -d

# --- 5. Wait for health ----------------------------------------------------
info "Waiting for the API to become healthy"
HEALTH_URL="http://localhost:${BILLING_PORT}/health"
for i in $(seq 1 30); do
  if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
    ok "API is healthy at $HEALTH_URL"
    echo
    ok "Qora Billing is up. Manage it from $(pwd) with: docker compose [logs|down|up -d]"
    exit 0
  fi
  sleep 2
done

err "API did not become healthy in time. Check logs: (cd $(pwd) && docker compose logs billing-api)"
exit 1
