#!/usr/bin/env bash
# ============================================================================
# SriYa API — one-line self-host installer.
#
#   curl -fsSL https://raw.githubusercontent.com/JJQuispillo/SriYa/main/install.sh | bash
#
# What it does:
#   1. Checks Docker + Docker Compose are available.
#   2. Downloads docker-compose.prod.yml.
#   3. Generates strong random secrets into .env (kept if it already exists).
#   4. Starts the stack and waits for /health.
#
# Env overrides (work even through `curl | bash`):
#   VERSION         release to install — pins both the image tag and the
#                   compose file (default: 1.0.0). Use "latest" + REF=main to
#                   track the bleeding edge.
#   INSTALL_DIR     target directory (default: ./qora-billing)
#   BILLING_PORT    host port for the API (default: 8080)
#   CORS_ORIGIN_0   allowed frontend origin (default: http://localhost:3000)
#   BILLING_DB_USER owner/bootstrap DB role (default: billing_user)
#   REF             git ref to pull files from (default: v<VERSION>)
#
# Run directly (`bash install.sh`) on a terminal to be prompted for the
# non-secret values instead of passing them as env vars. Secrets are ALWAYS
# random — never prompted.
# ============================================================================
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/JJQuispillo/SriYa"
VERSION="${VERSION:-1.0.0}"
# Pin the compose file to the matching git tag so a pinned image never gets an
# incompatible compose layout. Override REF explicitly to decouple them.
REF="${REF:-v${VERSION}}"
INSTALL_DIR="${INSTALL_DIR:-qora-billing}"
BILLING_PORT="${BILLING_PORT:-8080}"
CORS_ORIGIN_0="${CORS_ORIGIN_0:-http://localhost:3000}"
BILLING_DB_USER="${BILLING_DB_USER:-billing_user}"

info()  { printf '\033[1;34m==>\033[0m %s\n' "$1"; }
ok()    { printf '\033[1;32m✓\033[0m %s\n' "$1"; }
err()   { printf '\033[1;31m✗ %s\033[0m\n' "$1" >&2; }

# --- 1. Preflight ----------------------------------------------------------
command -v docker >/dev/null 2>&1 || { err "Docker not found. Install Docker first: https://docs.docker.com/get-docker/"; exit 1; }
if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose v2 not found. Update Docker or install the compose plugin."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  err "Docker daemon is not running. Start Docker and re-run."
  exit 1
fi
ok "Docker is ready"

# Charset-safe secret: alphanumeric only. Avoids '+', '/', '=' from base64,
# which break Npgsql connection-string parsing and SQL role passwords.
# 44 chars from [A-Za-z0-9] ≈ 262 bits of entropy. No openssl dependency.
gen_secret() {
  local s
  s=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom 2>/dev/null | head -c 44) || true
  printf '%s' "$s"
}

# --- Optional interactive config (skipped under `curl | bash`) --------------
# When piped, stdin is the script — not a terminal — so `[ -t 0 ]` is false and
# these prompts are skipped, falling back to env vars / defaults. Secrets are
# never prompted; they are always random.
if [ -t 0 ]; then
  printf '\n'
  info "Configuración (Enter para aceptar el valor entre corchetes):"
  read -rp "  Puerto del API en el host [${BILLING_PORT}]: " _ans || true
  BILLING_PORT="${_ans:-$BILLING_PORT}"; _ans=
  read -rp "  Origen CORS del frontend [${CORS_ORIGIN_0}]: " _ans || true
  CORS_ORIGIN_0="${_ans:-$CORS_ORIGIN_0}"; _ans=
  read -rp "  Usuario propietario de la BD [${BILLING_DB_USER}]: " _ans || true
  BILLING_DB_USER="${_ans:-$BILLING_DB_USER}"; _ans=
  printf '\n'
fi

# --- 2. Files --------------------------------------------------------------
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
info "Installing into $(pwd)"

if [ -f docker-compose.yml ]; then
  ok "docker-compose.yml already exists — leaving it untouched (your edits are safe)"
else
  info "Downloading docker-compose.yml"
  curl -fsSL "$REPO_RAW/$REF/docker-compose.prod.yml" -o docker-compose.yml
  ok "Compose file ready"
fi

# --- 3. Secrets / .env -----------------------------------------------------
if [ -f .env ]; then
  ok ".env already exists — leaving it untouched"
else
  info "Generating .env with random secrets"
  cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Review CORS_ORIGIN_0 before exposing this service publicly.

# Pinned image version. Bump this and 'docker compose pull && up -d' to upgrade.
BILLING_IMAGE_TAG=${VERSION}

BILLING_API_PORT=${BILLING_PORT}

# ─── Database (rol propietario/bootstrap) ────────────────
BILLING_DB_USER=${BILLING_DB_USER}
BILLING_DB_PASSWORD=$(gen_secret)

# ─── Runtime roles (RLS multi-emisor) ─────────────────────
BILLING_APP_DB_PASSWORD=$(gen_secret)
BILLING_PRIVILEGED_DB_PASSWORD=$(gen_secret)

# ─── Service-to-service auth ──────────────────────────────
SERVICE_AUTH_TOKEN=$(gen_secret)

# ─── Certificate-key encryption (at rest) ─────────────────
ENCRYPTION_KEY=$(gen_secret)

# ─── CORS ─────────────────────────────────────────────────
CORS_ORIGIN_0=${CORS_ORIGIN_0}
EOF
  chmod 600 .env
  ok "Secrets written to .env (chmod 600)"
fi

# --- 4. Launch -------------------------------------------------------------
info "Pulling images and starting the stack"
if ! docker compose pull; then
  err "No se pudo descargar la imagen (versión: ${VERSION})."
  err "Causas comunes: el package de GHCR no es público, o '${VERSION}' no es un tag publicado."
  err "Revisa el detalle con: (cd $(pwd) && docker compose pull)"
  exit 1
fi
docker compose up -d

# --- 5. Wait for health ----------------------------------------------------
info "Waiting for the API to become healthy"
HEALTH_URL="http://localhost:${BILLING_PORT}/health"
# 45 × 2s = 90s. First boot pulls postgres, runs migrations and provisions roles.
for i in $(seq 1 45); do
  if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
    ok "API is healthy at $HEALTH_URL"
    echo

    # Pull the service token back out of .env so the next-step command is copy-paste ready.
    SERVICE_TOKEN="$(grep -E '^SERVICE_AUTH_TOKEN=' .env | cut -d= -f2-)"

    info "Next step — onboard your first emisor (tenant + .p12 certificate + API key, atomically):"
    cat <<EOF

  curl -X POST http://localhost:${BILLING_PORT}/api/v1/bootstrap \\
    -H "X-Service-Token: ${SERVICE_TOKEN}" \\
    -F ruc=<tu RUC> \\
    -F razonSocial="<tu razon social>" \\
    -F ownerName="<nombre del titular del certificado>" \\
    -F password="<password del .p12>" \\
    -F certificate=@/ruta/a/tu-certificado.p12

  → la respuesta incluye tenantId y apiKey EN CLARO una sola vez. Guarda la apiKey.

EOF
    ok "SriYa is up. Manage it from $(pwd) with: docker compose [logs|down|up -d]"
    exit 0
  fi
  sleep 2
done

err "API did not become healthy in time. Check logs: (cd $(pwd) && docker compose logs billing-api)"
exit 1
