// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qora.Billing.Infrastructure.Persistence;

#nullable disable

namespace Qora.Billing.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260510202818_AddSaasLayer")]
    partial class AddSaasLayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qora.Billing.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_api_keys_tenant_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Destinatario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodEstabDestino")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cod_estab_destino");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirDestinatario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dir_destinatario");

                    b.Property<string>("DocAduaneroUnico")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("doc_aduanero_unico");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("IdentificacionDestinatario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion_destinatario");

                    b.Property<string>("MotivoTraslado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_traslado");

                    b.Property<string>("RazonSocialDestinatario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("razon_social_destinatario");

                    b.Property<string>("Rise")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rise");

                    b.Property<string>("RucTransportista")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ruc_transportista");

                    b.Property<string>("RutaEntrega")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ruta_entrega");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_destinatarios_document_id");

                    b.ToTable("document_destinatarios", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.DestinatarioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CantidadDetalle")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("cantidad_detalle");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("codigo_interno");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescripcionDetalle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion_detalle");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinatario_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId")
                        .HasDatabaseName("ix_document_destinatario_items_destinatario_id");

                    b.ToTable("document_destinatario_items", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessKey")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("access_key");

                    b.Property<string>("BuyerInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("buyer_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IssuerInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issuer_info");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("SignedXmlContent")
                        .HasColumnType("text")
                        .HasColumnName("signed_xml_content");

                    b.Property<DateTime?>("SriAuthorizationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sri_authorization_date");

                    b.Property<string>("SriAuthorizationNumber")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("sri_authorization_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XmlContent")
                        .HasColumnType("text")
                        .HasColumnName("xml_content");

                    b.HasKey("Id");

                    b.HasIndex("AccessKey")
                        .IsUnique()
                        .HasDatabaseName("ix_documents_access_key")
                        .HasFilter("access_key IS NOT NULL");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_documents_tenant_id_status");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.DocumentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_events_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_document_events_tenant_id");

                    b.ToTable("document_events", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.DocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuxiliaryCode")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("auxiliary_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("MainCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("main_code");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("SustentoDocumentAuthNumber")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)")
                        .HasColumnName("sustento_document_auth_number");

                    b.Property<DateTime?>("SustentoDocumentIssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sustento_document_issue_date");

                    b.Property<string>("SustentoDocumentNumber")
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("sustento_document_number");

                    b.Property<string>("SustentoDocumentType")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("sustento_document_type");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tax_code");

                    b.Property<string>("TaxPercentageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tax_percentage_code");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_items_document_id");

                    b.ToTable("document_items", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.ElectronicSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertificateData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificate_data");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("owner_name");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_encrypted");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_electronic_signatures_tenant_id");

                    b.ToTable("electronic_signatures", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentLimit")
                        .HasColumnType("integer")
                        .HasColumnName("document_limit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceMonthlyUsd")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_monthly_usd");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_price_id");

                    b.Property<string>("StripeProductId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_product_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_slug");

                    b.ToTable("plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentLimit = 50,
                            IsActive = true,
                            Name = "Free",
                            PriceMonthlyUsd = 0.00m,
                            Slug = "free",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentLimit = 500,
                            IsActive = true,
                            Name = "Basic",
                            PriceMonthlyUsd = 29.00m,
                            Slug = "basic",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentLimit = -1,
                            IsActive = true,
                            Name = "Pro",
                            PriceMonthlyUsd = 99.00m,
                            Slug = "pro",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.SriTaxCode", b =>
                {
                    b.Property<string>("TaxTypeCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tax_type_code");

                    b.Property<string>("PercentageCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("percentage_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Rate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("rate");

                    b.HasKey("TaxTypeCode", "PercentageCode");

                    b.ToTable("sri_tax_codes", (string)null);

                    b.HasData(
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "0",
                            Description = "IVA 0%",
                            IsActive = true,
                            Rate = 0m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "2",
                            Description = "IVA 12%",
                            IsActive = true,
                            Rate = 12m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "3",
                            Description = "IVA 14% (histórico)",
                            IsActive = false,
                            Rate = 14m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "4",
                            Description = "IVA 15%",
                            IsActive = true,
                            Rate = 15m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "5",
                            Description = "IVA 5%",
                            IsActive = true,
                            Rate = 5m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "6",
                            Description = "No Objeto de IVA",
                            IsActive = true,
                            Rate = 0m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "7",
                            Description = "Exento de IVA",
                            IsActive = true,
                            Rate = 0m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "8",
                            Description = "IVA 8% (histórico)",
                            IsActive = false,
                            Rate = 8m
                        },
                        new
                        {
                            TaxTypeCode = "2",
                            PercentageCode = "10",
                            Description = "IVA 10% (histórico)",
                            IsActive = false,
                            Rate = 10m
                        },
                        new
                        {
                            TaxTypeCode = "3",
                            PercentageCode = "3011",
                            Description = "ICE Cigarrillos",
                            IsActive = true,
                            Rate = 75m
                        },
                        new
                        {
                            TaxTypeCode = "3",
                            PercentageCode = "3023",
                            Description = "ICE Cerveza (L)",
                            IsActive = true,
                            Rate = 0.15m
                        },
                        new
                        {
                            TaxTypeCode = "3",
                            PercentageCode = "3041",
                            Description = "ICE Vehículos < $20k",
                            IsActive = true,
                            Rate = 35m
                        },
                        new
                        {
                            TaxTypeCode = "3",
                            PercentageCode = "3072",
                            Description = "ICE Bebidas alcohólicas",
                            IsActive = true,
                            Rate = 9m
                        },
                        new
                        {
                            TaxTypeCode = "5",
                            PercentageCode = "5001",
                            Description = "IRBPNR",
                            IsActive = true,
                            Rate = 0.02m
                        },
                        new
                        {
                            TaxTypeCode = "6",
                            PercentageCode = "6001",
                            Description = "ISD 5%",
                            IsActive = true,
                            Rate = 5m
                        },
                        new
                        {
                            TaxTypeCode = "1",
                            PercentageCode = "303",
                            Description = "Ret. Renta 1%",
                            IsActive = true,
                            Rate = 1m
                        },
                        new
                        {
                            TaxTypeCode = "1",
                            PercentageCode = "304",
                            Description = "Ret. Renta 1.75%",
                            IsActive = true,
                            Rate = 1.75m
                        },
                        new
                        {
                            TaxTypeCode = "1",
                            PercentageCode = "312",
                            Description = "Ret. Renta 2%",
                            IsActive = true,
                            Rate = 2m
                        },
                        new
                        {
                            TaxTypeCode = "1",
                            PercentageCode = "322",
                            Description = "Ret. Renta 8%",
                            IsActive = true,
                            Rate = 8m
                        },
                        new
                        {
                            TaxTypeCode = "1",
                            PercentageCode = "332",
                            Description = "Ret. Renta 10%",
                            IsActive = true,
                            Rate = 10m
                        },
                        new
                        {
                            TaxTypeCode = "1",
                            PercentageCode = "343",
                            Description = "Ret. Renta 30%",
                            IsActive = true,
                            Rate = 30m
                        });
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("StripeSubscriptionId")
                        .HasDatabaseName("ix_subscriptions_stripe_subscription_id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_tenant_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("business_name");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EmailEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_enabled");

                    b.Property<int>("EmailProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("email_provider");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ruc");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_name");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("smtp_host");

                    b.Property<string>("SmtpPassword")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("smtp_password");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("smtp_port");

                    b.Property<string>("SmtpUser")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("smtp_user");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<string>("TradeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("trade_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseSsl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("use_ssl");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_ruc");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.UsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("billing_period");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_usage_records_document_id");

                    b.HasIndex("TenantId", "BillingPeriod")
                        .HasDatabaseName("ix_usage_records_tenant_id_billing_period");

                    b.ToTable("usage_records", (string)null);
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Destinatario", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Document", null)
                        .WithMany("Destinatarios")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.DestinatarioItem", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Destinatario", null)
                        .WithMany("Items")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Document", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.DocumentEvent", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.DocumentItem", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Document", null)
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.ElectronicSignature", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qora.Billing.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Subscription")
                        .HasForeignKey("Qora.Billing.Domain.Entities.Subscription", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.UsageRecord", b =>
                {
                    b.HasOne("Qora.Billing.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Destinatario", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Document", b =>
                {
                    b.Navigation("Destinatarios");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Qora.Billing.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
