namespace Qora.Billing.Infrastructure.Xml;

/// <summary>
/// Shared constants for Comprobante de Retención document processing.
/// Used by both ComprobanteRetencionStrategy (validation) and ComprobanteRetencionXmlBuilder
/// (XML generation) to ensure alignment between validated and required fields.
/// </summary>
public static class ComprobanteRetencionConstants
{
    /// <summary>
    /// Issuer fields that must be provided by the API caller (not auto-generated).
    /// Includes periodoFiscal which is retention-specific (format MM/YYYY).
    /// </summary>
    public static readonly string[] RequiredIssuerFields =
    [
        "ruc",
        "razonSocial",
        "dirMatriz",
        "estab",
        "ptoEmi",
        "secuencial",
        "periodoFiscal"
    ];

    /// <summary>
    /// Buyer (sujeto retenido) fields required by ComprobanteRetencionXmlBuilder
    /// for the infoCompRetencion section.
    /// </summary>
    public static readonly string[] RequiredBuyerFields =
    [
        "tipoIdentificacion",
        "razonSocial",
        "identificacion"
    ];

    /// <summary>
    /// Issuer fields that are auto-generated by the system before XML generation.
    /// These should NOT be required from the API caller.
    /// </summary>
    public static readonly string[] SystemGeneratedIssuerFields =
    [
        "ambiente",
        "tipoEmision",
        "claveAcceso",
        "fechaEmision"
    ];

    /// <summary>
    /// All issuer fields required by ComprobanteRetencionXmlBuilder (caller-provided + system-generated).
    /// </summary>
    public static readonly string[] AllRequiredIssuerFields =
    [
        .. RequiredIssuerFields,
        .. SystemGeneratedIssuerFields
    ];

    /// <summary>
    /// Valid SRI tax type codes for retenciones:
    /// "1" = Retención en la Fuente (Renta)
    /// "2" = Retención IVA
    /// "6" = Retención ISD (Impuesto a la Salida de Divisas)
    /// Maps to DocumentItem.TaxCode.
    /// </summary>
    public static readonly HashSet<string> ValidTaxCodes = ["1", "2", "6"];

    /// <summary>
    /// Valid SRI document types that can sustain a retention (codDocSustento).
    /// "01" = Factura, "03" = Liquidación de Compra, "04" = Nota de Crédito,
    /// "05" = Nota de Débito, "07" = Comprobante de Retención,
    /// "41" = Comprobante de Venta emitido en el Exterior, "43" = Liquidación de Compra emitida por el adquirente.
    /// </summary>
    public static readonly HashSet<string> ValidDocSustentoTypes =
    [
        "01", "03", "04", "05", "07", "41", "43"
    ];
}
