namespace Qora.Billing.Infrastructure.Xml;

/// <summary>
/// Shared constants for Factura document processing.
/// Used by both FacturaStrategy (validation) and FacturaXmlBuilder (XML generation)
/// to ensure alignment between validated and required fields.
/// </summary>
public static class FacturaConstants
{
    /// <summary>
    /// Issuer fields that must be provided by the API caller (not auto-generated).
    /// </summary>
    public static readonly string[] RequiredIssuerFields =
    [
        "ruc",
        "razonSocial",
        "dirMatriz",
        "estab",
        "ptoEmi",
        "secuencial"
    ];

    /// <summary>
    /// Issuer fields that are auto-generated by the system before XML generation.
    /// These should NOT be required from the API caller.
    /// </summary>
    public static readonly string[] SystemGeneratedIssuerFields =
    [
        "ambiente",
        "tipoEmision",
        "claveAcceso",
        "fechaEmision"
    ];

    /// <summary>
    /// All issuer fields required by FacturaXmlBuilder (caller-provided + system-generated).
    /// </summary>
    public static readonly string[] AllRequiredIssuerFields =
    [
        .. RequiredIssuerFields,
        .. SystemGeneratedIssuerFields
    ];

    /// <summary>
    /// Buyer fields required by FacturaXmlBuilder for the infoFactura section.
    /// Only enforced when buyer identification is mandatory (e.g., total > $200).
    /// </summary>
    public static readonly string[] RequiredBuyerFields =
    [
        "tipoIdentificacion",
        "razonSocial",
        "identificacion"
    ];
}
