namespace Qora.Billing.Infrastructure.Xml;

/// <summary>
/// Shared constants for Guía de Remisión document processing.
/// Used by both GuiaRemisionStrategy (validation) and GuiaRemisionXmlBuilder (XML generation)
/// to ensure alignment between validated and required fields.
/// </summary>
public static class GuiaRemisionConstants
{
    // ── XML element name constants ───────────────────────────────────────────
    public const string DestinatariosTag = "destinatarios";
    public const string DestinatarioTag = "destinatario";
    public const string IdentificacionDestinatarioTag = "identificacionDestinatario";
    public const string RazonSocialDestinatarioTag = "razonSocialDestinatario";
    public const string DirDestinatarioTag = "dirDestinatario";
    public const string MotivoTrasladoTag = "motivoTraslado";
    public const string RutaTag = "ruta";
    public const string DocAduaneroUnicoTag = "docAduaneroUnico";
    public const string CodEstabDestinoTag = "codEstabDestino";
    public const string CodDocSustentoTag = "codDocSustento";
    public const string NumDocSustentoTag = "numDocSustento";
    public const string NumAutDocSustentoTag = "numAutDocSustento";
    public const string FechaEmisionDocSustentoTag = "fechaEmisionDocSustento";
    public const string DetallesTag = "detalles";
    public const string DetalleTag = "detalle";
    public const string CodigoInternoTag = "codigoInterno";
    public const string DescripcionDetalleTag = "descripcionDetalle";
    public const string CantidadDetalleTag = "cantidadDetalle";


    /// <summary>
    /// Issuer fields that must be provided by the API caller (not auto-generated).
    /// </summary>
    public static readonly string[] RequiredIssuerFields =
    [
        "ruc",
        "razonSocial",
        "dirMatriz",
        "estab",
        "ptoEmi",
        "secuencial"
    ];

    /// <summary>
    /// Transporter fields that must be provided in IssuerInfo by the API caller.
    /// </summary>
    public static readonly string[] RequiredTransporterFields =
    [
        "razonSocialTransportista",
        "rucTransportista",
        "obligadoContabilidad",
        "fechaInicioTransporte",
        "fechaFinTransporte",
        "placa"
    ];

    /// <summary>
    /// Optional transporter fields in IssuerInfo (included in XML only when present).
    /// </summary>
    public static readonly string[] OptionalTransporterFields =
    [
        "rise",
        "contribuyenteEspecial"
    ];

    /// <summary>
    /// Destinatario fields required in BuyerInfo by the API caller (legacy single-destinatario path only).
    /// When Destinatarios are provided as entities, per-entity identity fields are validated by the strategy.
    /// </summary>
    public static readonly string[] RequiredDestinatarioFields =
    [
        "identificacionDestinatario",
        "razonSocialDestinatario",
        "dirDestinatario",
        "motivoTraslado",
        "codDocSustento",
        "numDocSustento",
        "numAutDocSustento",
        "fechaEmisionDocSustento"
    ];

    /// <summary>
    /// Sustento document fields in BuyerInfo required for multi-destinatario documents.
    /// These are document-level (shared across all destinatarios) because the Destinatario
    /// entity does not yet carry them.
    /// </summary>
    public static readonly string[] RequiredSustentoDocFields =
    [
        "codDocSustento",
        "numDocSustento"
    ];

    /// <summary>
    /// Optional destinatario fields in BuyerInfo (included in XML only when present).
    /// </summary>
    public static readonly string[] OptionalDestinatarioFields =
    [
        "docAduaneroUnico",
        "codEstabDestino",
        "ruta"
    ];

    /// <summary>
    /// Issuer fields that are auto-generated by the system before XML generation.
    /// These should NOT be required from the API caller.
    /// </summary>
    public static readonly string[] SystemGeneratedIssuerFields =
    [
        "ambiente",
        "tipoEmision",
        "claveAcceso",
        "fechaEmision"
    ];

    /// <summary>
    /// All issuer fields required by GuiaRemisionXmlBuilder (caller-provided + system-generated).
    /// </summary>
    public static readonly string[] AllRequiredIssuerFields =
    [
        .. RequiredIssuerFields,
        .. SystemGeneratedIssuerFields
    ];
}
