namespace Qora.Billing.Infrastructure.Xml;

/// <summary>
/// Shared constants for Liquidación de Compra document processing.
/// Used by both LiquidacionCompraStrategy (validation) and LiquidacionCompraXmlBuilder (XML generation)
/// to ensure alignment between validated and required fields.
/// </summary>
public static class LiquidacionCompraConstants
{
    /// <summary>
    /// Issuer fields that must be provided by the API caller (not auto-generated).
    /// </summary>
    public static readonly string[] RequiredIssuerFields =
    [
        "ruc",
        "razonSocial",
        "dirMatriz",
        "estab",
        "ptoEmi",
        "secuencial"
    ];

    /// <summary>
    /// Provider fields that must be present in BuyerInfo for a Liquidación de Compra.
    /// In this document type, the "buyer" role is filled by the provider (proveedor).
    /// </summary>
    public static readonly string[] RequiredProviderFields =
    [
        "tipoIdentificacionProveedor",
        "razonSocialProveedor",
        "identificacionProveedor",
        "direccionProveedor"
    ];

    /// <summary>
    /// Issuer fields that are auto-generated by the system before XML generation.
    /// These should NOT be required from the API caller.
    /// </summary>
    public static readonly string[] SystemGeneratedIssuerFields =
    [
        "ambiente",
        "tipoEmision",
        "claveAcceso",
        "fechaEmision"
    ];

    /// <summary>
    /// All issuer fields required by LiquidacionCompraXmlBuilder (caller-provided + system-generated).
    /// </summary>
    public static readonly string[] AllRequiredIssuerFields =
    [
        .. RequiredIssuerFields,
        .. SystemGeneratedIssuerFields
    ];

    /// <summary>
    /// Valid SRI identification type codes for providers in a Liquidación de Compra.
    /// 04=RUC, 05=Cédula, 06=Pasaporte, 07=Consumidor Final, 08=Identificación Exterior, 09=Placa.
    /// </summary>
    public static readonly HashSet<string> ValidProviderIdTypes =
    [
        "04",
        "05",
        "06",
        "07",
        "08",
        "09"
    ];

    /// <summary>
    /// Optional retention fields checked in IssuerInfo.
    /// If "codigoRetencion" is present, all three must be present.
    /// </summary>
    public static readonly string[] RetentionFields =
    [
        "codigoRetencion",
        "porcentajeRetencion",
        "valorRetencion"
    ];
}
