namespace Qora.Billing.Infrastructure.Xml;

/// <summary>
/// Shared constants for Nota de Crédito document processing.
/// Used by both NotaCreditoStrategy (validation) and NotaCreditoXmlBuilder (XML generation)
/// to ensure alignment between validated and required fields.
/// </summary>
public static class NotaCreditoConstants
{
    /// <summary>
    /// Issuer fields that must be provided by the API caller (not auto-generated).
    /// </summary>
    public static readonly string[] RequiredIssuerFields =
    [
        "ruc",
        "razonSocial",
        "dirMatriz",
        "estab",
        "ptoEmi",
        "secuencial"
    ];

    /// <summary>
    /// Fields describing the document being modified (sustento), required for credit notes.
    /// </summary>
    public static readonly string[] RequiredDocSustentoFields =
    [
        "codDocModificado",
        "numDocModificado",
        "fechaEmisionDocSustento",
        "razonModificacion"
    ];

    /// <summary>
    /// Issuer fields that are auto-generated by the system before XML generation.
    /// These should NOT be required from the API caller.
    /// </summary>
    public static readonly string[] SystemGeneratedIssuerFields =
    [
        "ambiente",
        "tipoEmision",
        "claveAcceso",
        "fechaEmision"
    ];

    /// <summary>
    /// All issuer fields required by NotaCreditoXmlBuilder (caller-provided + system-generated).
    /// </summary>
    public static readonly string[] AllRequiredIssuerFields =
    [
        .. RequiredIssuerFields,
        .. SystemGeneratedIssuerFields
    ];

    /// <summary>
    /// Buyer fields required by NotaCreditoXmlBuilder for the infoNotaCredito section.
    /// </summary>
    public static readonly string[] RequiredBuyerFields =
    [
        "tipoIdentificacion",
        "razonSocial",
        "identificacion"
    ];

    /// <summary>
    /// Document type codes that can be credit-noted.
    /// Only Facturas (01) are supported in the base case.
    /// </summary>
    public static readonly string[] ValidDocModificadoCodes =
    [
        "01"
    ];
}
