namespace Qora.Billing.Infrastructure.Xml;

/// <summary>
/// Shared constants for Nota de Débito document processing.
/// Used by both NotaDebitoStrategy (validation) and NotaDebitoXmlBuilder (XML generation)
/// to ensure alignment between validated and required fields.
/// </summary>
public static class NotaDebitoConstants
{
    /// <summary>
    /// Issuer fields that must be provided by the API caller (not auto-generated).
    /// </summary>
    public static readonly string[] RequiredIssuerFields =
    [
        "ruc",
        "razonSocial",
        "dirMatriz",
        "estab",
        "ptoEmi",
        "secuencial"
    ];

    /// <summary>
    /// Document sustento fields that must be provided by the API caller.
    /// Nota de Débito always references a sustaining document (e.g., an original Factura).
    /// </summary>
    public static readonly string[] RequiredDocSustentoFields =
    [
        "codDocSustento",
        "numDocSustento",
        "fechaEmisionDocSustento"
    ];

    /// <summary>
    /// Issuer fields that are auto-generated by the system before XML generation.
    /// These should NOT be required from the API caller.
    /// </summary>
    public static readonly string[] SystemGeneratedIssuerFields =
    [
        "ambiente",
        "tipoEmision",
        "claveAcceso",
        "fechaEmision"
    ];

    /// <summary>
    /// All issuer fields required by NotaDebitoXmlBuilder (caller-provided + system-generated).
    /// Does not include RequiredDocSustentoFields (also in IssuerInfo, validated separately).
    /// </summary>
    public static readonly string[] AllRequiredIssuerFields =
    [
        .. RequiredIssuerFields,
        .. SystemGeneratedIssuerFields
    ];

    /// <summary>
    /// Buyer fields required by NotaDebitoXmlBuilder for the infoNotaDebito section.
    /// </summary>
    public static readonly string[] RequiredBuyerFields =
    [
        "tipoIdentificacion",
        "razonSocial",
        "identificacion"
    ];
}
